#!/usr/bin/env bash

smoke_host "vagalume.org.br"

smoke_message 'vagalume.org.br/doe redireciona para vagalume.colabore.org/'
smoke_url '/doe'
smoke_assert_code 302
smoke_assert_headers '^Location: https://vagalume.colabore.org'

smoke_message 'vagalume.org.br/en/donate redireciona para globalgiving'
smoke_url '/donate'
smoke_assert_code 302
smoke_assert_headers '^Location: https://www.globalgiving.org/projects/quality-education-to-15000-amazon-children/?show=recurring'

smoke_host "staging.vagalume.org.br"

smoke_message 'staging.vagalume.org.br/doe redireciona para vagalume.colabore.org'
smoke_url '/doe'
smoke_assert_code 302
smoke_assert_headers '^Location: https://vagalume.colabore.org'

smoke_message 'staging.vagalume.org.br/doe redireciona para globalgiving'
smoke_url '/donate'
smoke_assert_code 302
smoke_assert_headers '^Location: https://www.globalgiving.org/projects/quality-education-to-15000-amazon-children/?show=recurring'

smoke_host $SERVIDOR
