#!/usr/bin/env bash

smoke_no_follow

smoke_message 'A página /proposito existe'
smoke_url_ok '/proposito/'
smoke_assert_body "<title>Propósito | Vaga Lume - Empoderando crianças na Amazônia</title>"
smoke_assert_body '<h1>Propósito</h1>'