#!/usr/bin/env bash

smoke_message 'A página /parceiros existe'
smoke_url_ok '/parceiros/'
smoke_assert_body "description.*content=\"Descubra quem são as empresas que, \
assim como nós, acreditam no empoderamento das crianças da Amazônia e \
apoiam essa causa.\""
smoke_assert_body "<title>Parceiros | Vaga Lume - Empoderando crianças na Amazônia</title>"
smoke_assert_body '<h1>Parceiros</h1>'
